version: "3.8"
services:
  sonarqube:
    image: harbor.royfuwei.com/tools/ts-react-arch
    container_name: ts-react-arch
    restart: always
    networks:
      - devops

networks:
  devops:
    external: true